spring:
  application:
    name: employee-manager
  datasource:
    url: jdbc:postgresql://localhost:5432/employee-manager-db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/database_emp_manager_changelog.xml
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/employee-manager-db
    user: user
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
feign:
  resume-manager:
    url: http://localhost:8080/resume-manager
